# Generated by Django 5.0.6 on 2024-05-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora_principal',
            name='TRADE_DATE',
            field=models.DateTimeField(default='2024-05-08'),
        ),
        migrations.AlterField(
            model_name='historial_bitacora',
            name='TRADE_DATE',
            field=models.DateTimeField(default='2024-05-08'),
        ),
    ]
